# Northwind Traders — Data Exploration & Cleaning

Reading, inspecting, and cleaning the master dataset: `northwind_master.csv`

## 1. Import Library

In [1]:
import pandas as pd
import numpy as np

print('pandas version:', pd.__version__)

pandas version: 2.3.3

## 2. Load Dataset

In [2]:
df = pd.read_csv(r'D:\Intern Project\Northwind Traders\northwind_master.csv')

print('Dataset loaded successfully.')
print('Shape:', df.shape)

Dataset loaded successfully.
Shape: (2155, 35)

## 3. View Full DataFrame

In [3]:
df

,orderID,productID,unitPrice,quantity,discount,productName,quantityPerUnit,product_unitPrice,categoryID,discontinued,...,employee_title,employee_city,employee_country,reports_to,shipper_name,line_total,order_year,order_month,order_quarter,ship_delay_days
0,10248,11,14.00,12,0.00,Queso Cabrales,1 kg pkg.,21.00,4,0,...,Sales Manager,London,UK,2.0,Federal Shipping,168.000,2013,7,3,12.0
1,10248,42,9.80,10,0.00,Singaporean Hokkien Fried Mee,32 - 1 kg pkgs.,14.00,5,1,...,Sales Manager,London,UK,2.0,Federal Shipping,98.000,2013,7,3,12.0
2,10248,72,34.80,5,0.00,Mozzarella di Giovanni,24 - 200 g pkgs.,34.80,4,0,...,Sales Manager,London,UK,2.0,Federal Shipping,174.000,2013,7,3,12.0
3,10249,14,18.60,9,0.00,Tofu,40 - 100 g pkgs.,23.25,7,0,...,Sales Representative,London,UK,5.0,Speedy Express,167.400,2013,7,3,5.0
4,10249,51,42.40,40,0.00,Manjimup Dried Apples,50 - 300 g pkgs.,53.00,7,0,...,Sales Representative,London,UK,5.0,Speedy Express,1696.000,2013,7,3,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2150,11077,64,33.25,2,0.03,Wimmers gute Semmelknödel,20 bags x 4 pieces,33.25,5,0,...,Sales Representative,New York,USA,8.0,United Package,64.505,2015,5,2,NaN
2151,11077,66,17.00,1,0.00,Louisiana Hot Spiced Okra,24 - 8 oz jars,17.00,2,0,...,Sales Representative,New York,USA,8.0,United Package,17.000,2015,5,2,NaN
2152,11077,73,15.00,2,0.01,Röd Kaviar,24 - 150 g jars,15.00,8,0,...,Sales Representative,New York,USA,8.0,United Package,29.700,2015,5,2,NaN
2153,11077,75,7.75,4,0.00,Rhönbräu Klosterbier,24 - 0.5 l bottles,7.75,1,0,...,Sales Representative,New York,USA,8.0,United Package,31.000,2015,5,2,NaN
2154,11077,77,13.00,2,0.00,Original Frankfurter Grüne Soße,12 boxes,13.00,2,0,...,Sales Representative,New York,USA,8.0,United Package,26.000,2015,5,2,NaN

## 4. First 5 Rows

In [4]:
df.head()

,orderID,productID,unitPrice,quantity,discount,productName,quantityPerUnit,product_unitPrice,categoryID,discontinued,...,employee_title,employee_city,employee_country,reports_to,shipper_name,line_total,order_year,order_month,order_quarter,ship_delay_days
0,10248,11,14.0,12,0.0,Queso Cabrales,1 kg pkg.,21.00,4,0,...,Sales Manager,London,UK,2.0,Federal Shipping,168.0,2013,7,3,12.0
1,10248,42,9.8,10,0.0,Singaporean Hokkien Fried Mee,32 - 1 kg pkgs.,14.00,5,1,...,Sales Manager,London,UK,2.0,Federal Shipping,98.0,2013,7,3,12.0
2,10248,72,34.8,5,0.0,Mozzarella di Giovanni,24 - 200 g pkgs.,34.80,4,0,...,Sales Manager,London,UK,2.0,Federal Shipping,174.0,2013,7,3,12.0
3,10249,14,18.6,9,0.0,Tofu,40 - 100 g pkgs.,23.25,7,0,...,Sales Representative,London,UK,5.0,Speedy Express,167.4,2013,7,3,5.0
4,10249,51,42.4,40,0.0,Manjimup Dried Apples,50 - 300 g pkgs.,53.00,7,0,...,Sales Representative,London,UK,5.0,Speedy Express,1696.0,2013,7,3,5.0

## 5. Last 5 Rows

In [5]:
df.tail()

,orderID,productID,unitPrice,quantity,discount,productName,quantityPerUnit,product_unitPrice,categoryID,discontinued,...,employee_title,employee_city,employee_country,reports_to,shipper_name,line_total,order_year,order_month,order_quarter,ship_delay_days
2150,11077,64,33.25,2,0.03,Wimmers gute Semmelknödel,20 bags x 4 pieces,33.25,5,0,...,Sales Representative,New York,USA,8.0,United Package,64.505,2015,5,2,NaN
2151,11077,66,17.00,1,0.00,Louisiana Hot Spiced Okra,24 - 8 oz jars,17.00,2,0,...,Sales Representative,New York,USA,8.0,United Package,17.000,2015,5,2,NaN
2152,11077,73,15.00,2,0.01,Röd Kaviar,24 - 150 g jars,15.00,8,0,...,Sales Representative,New York,USA,8.0,United Package,29.700,2015,5,2,NaN
2153,11077,75,7.75,4,0.00,Rhönbräu Klosterbier,24 - 0.5 l bottles,7.75,1,0,...,Sales Representative,New York,USA,8.0,United Package,31.000,2015,5,2,NaN
2154,11077,77,13.00,2,0.00,Original Frankfurter Grüne Soße,12 boxes,13.00,2,0,...,Sales Representative,New York,USA,8.0,United Package,26.000,2015,5,2,NaN

## 6. Column Names

In [6]:
df.columns

Index(['orderID', 'productID', 'unitPrice', 'quantity', 'discount',
       'productName', 'quantityPerUnit', 'product_unitPrice', 'categoryID',
       'discontinued', 'categoryName', 'category_description', 'customerID',
       'employeeID', 'orderDate', 'requiredDate', 'shippedDate', 'shipperID',
       'freight', 'customer_company', 'customer_contact', 'customer_title',
       'customer_city', 'customer_country', 'employee_name', 'employee_title',
       'employee_city', 'employee_country', 'reports_to', 'shipper_name',
       'line_total', 'order_year', 'order_month', 'order_quarter',
       'ship_delay_days'],
      dtype='object')

## 7. Dataset Info (Column Types + Non-Null Count)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2155 entries, 0 to 2154
Data columns (total 35 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   orderID               2155 non-null   int64
 1   productID             2155 non-null   int64
 2   unitPrice             2155 non-null   float64
 3   quantity              2155 non-null   int64
 4   discount              2155 non-null   float64
 5   productName           2155 non-null   object
 6   quantityPerUnit       2155 non-null   object
 7   product_unitPrice     2155 non-null   float64
 8   categoryID            2155 non-null   int64
 9   discontinued          2155 non-null   int64
 10  categoryName          2155 non-null   object
 11  category_description  2155 non-null   object
 12  customerID            2155 non-null   object
 13  employeeID            2155 non-null   int64
 14  orderDate             2155 non-null   object
 15  requiredDate          2155 non-null   object
 16  shippedDate           2082 non-null   object
 17  shipperID             2155 non-null   int64
 18  freight               2155 non-null   float64
 19  customer_company      2155 non-null   object
 20  customer_contact      2155 non-null   object
 21  customer_title        2155 non-null   object
 22  customer_city         2155 non-null   object
 23  customer_country      2155 non-null   object
 24  employee_name         2155 non-null   object
 25  employee_title        2155 non-null   object
 26  employee_city         2155 non-null   object
 27  employee_country      2155 non-null   object
 28  reports_to            1914 non-null   float64
 29  shipper_name          2155 non-null   object
 30  line_total            2155 non-null   float64
 31  order_year            2155 non-null   int64
 32  order_month           2155 non-null   int64
 33  order_quarter         2155 non-null   int64
 34  ship_delay_days       2082 non-null   float64
dtypes: float64(7), int64(10), object(18)
memory usage: 589.4+ KB

## 8. Data Types

In [8]:
df.dtypes

orderID                   int64
productID                 int64
unitPrice               float64
quantity                  int64
discount                float64
productName              object
quantityPerUnit          object
product_unitPrice       float64
categoryID                int64
discontinued              int64
categoryName             object
category_description     object
customerID               object
employeeID                int64
orderDate                object
requiredDate             object
shippedDate              object
shipperID                 int64
freight                 float64
customer_company         object
customer_contact         object
customer_title           object
customer_city            object
customer_country         object
employee_name            object
employee_title           object
employee_city            object
employee_country         object
reports_to              float64
shipper_name             object
line_total              float64
order_year                int64
order_month               int64
order_quarter             int64
ship_delay_days         float64
dtype: object

## 9. Shape — Rows and Columns

In [9]:
print('Rows    :', df.shape[0])
print('Columns :', df.shape[1])

Rows    : 2155
Columns : 35

## 10. Missing Values

In [10]:
df.isnull().sum()

orderID                   0
productID                 0
unitPrice                 0
quantity                  0
discount                  0
productName               0
quantityPerUnit           0
product_unitPrice         0
categoryID                0
discontinued              0
categoryName              0
category_description      0
customerID                0
employeeID                0
orderDate                 0
requiredDate              0
shippedDate              73
shipperID                 0
freight                   0
customer_company          0
customer_contact          0
customer_title            0
customer_city             0
customer_country          0
employee_name             0
employee_title            0
employee_city             0
employee_country          0
reports_to              241
shipper_name              0
line_total                0
order_year                0
order_month               0
order_quarter             0
ship_delay_days          73
dtype: int64

## 11. Missing Values — Percentage

In [11]:
missing_pct = (df.isnull().sum() / len(df) * 100).round(2)
missing_pct[missing_pct > 0]

shippedDate         3.39
reports_to         11.18
ship_delay_days     3.39
dtype: float64

## 12. Duplicate Rows

In [12]:
print('Duplicate rows:', df.duplicated().sum())

Duplicate rows: 0

## 13. Statistical Summary — Numeric Columns

In [13]:
df.describe()

,orderID,productID,unitPrice,quantity,discount,product_unitPrice,categoryID,discontinued,employeeID,shipperID,freight,reports_to,line_total,order_year,order_month,order_quarter,ship_delay_days
count,2155.000000,2155.000000,2155.000000,2155.000000,2155.000000,2155.000000,2155.000000,2155.000000,2155.000000,2155.000000,2155.000000,1914.000000,2155.000000,2155.000000,2155.000000,2155.000000,2082.000000
mean,10659.375870,40.793039,26.218520,23.812993,0.056167,27.948687,4.135499,0.105800,4.333179,1.999536,96.197726,6.111285,587.374960,2014.132715,6.059397,2.374014,8.345341
std,241.378032,22.159019,29.827418,19.022047,0.083450,31.610706,2.378567,0.307653,2.490351,0.774177,133.011272,2.376406,969.224235,0.700856,3.637624,1.169987,6.692846
min,10248.000000,1.000000,2.000000,1.000000,0.000000,2.500000,1.000000,0.000000,1.000000,1.000000,0.020000,2.000000,4.800000,2013.000000,1.000000,1.000000,1.000000
25%,10451.000000,22.000000,12.000000,10.000000,0.000000,12.500000,2.000000,0.000000,2.000000,1.000000,19.610000,5.000000,147.000000,2014.000000,3.000000,1.000000,4.000000
50%,10657.000000,41.000000,18.400000,20.000000,0.000000,19.450000,4.000000,0.000000,4.000000,2.000000,53.800000,8.000000,337.750000,2014.000000,5.000000,2.000000,7.000000
75%,10862.500000,60.000000,32.000000,30.000000,0.100000,34.000000,6.000000,0.000000,7.000000,3.000000,120.920000,8.000000,656.000000,2015.000000,9.000000,3.000000,9.000000
max,11077.000000,77.000000,263.500000,130.000000,0.250000,263.500000,8.000000,1.000000,9.000000,3.000000,1007.640000,8.000000,15810.000000,2015.000000,12.000000,4.000000,37.000000

## 14. Statistical Summary — Object (Text) Columns

In [14]:
df.describe(include='object')

,productName,quantityPerUnit,categoryName,category_description,customerID,orderDate,requiredDate,shippedDate,customer_company,customer_contact,customer_title,customer_city,customer_country,employee_name,employee_title,employee_city,employee_country,shipper_name
count,2155,2155,2155,2155,2155,2155,2155,2082,2155,2155,2155,2155,2155,2155,2155,2155,2155,2155
unique,77,70,8,8,89,480,454,387,89,89,12,69,21,9,3,2,2,3
top,Raclette Courdavault,24 - 12 oz bottles,Beverages,"Soft drinks, coffees, teas, beers, and ales",SAVEA,2015-05-06,2015-06-03,2015-04-10,Save-a-lot Markets,Jose Pavarotti,Sales Representative,Boise,USA,Margaret Peacock,Sales Representative,New York,USA,United Package
freq,54,109,404,404,116,32,32,21,116,116,414,116,352,420,1537,1587,1587,864

## 15. Unique Values per Column

In [15]:
unique_counts = df.nunique().reset_index()
unique_counts.columns = ['Column', 'Unique Values']
unique_counts

                  Column  Unique Values
0                orderID            830
1              productID             77
2              unitPrice            116
3               quantity             55
4               discount             11
5            productName             77
6        quantityPerUnit             70
7      product_unitPrice             62
8             categoryID              8
9           discontinued              2
10          categoryName              8
11  category_description              8
12            customerID             89
13            employeeID              9
14             orderDate            480
15          requiredDate            454
16           shippedDate            387
17             shipperID              3
18               freight            799
19      customer_company             89
20      customer_contact             89
21        customer_title             12
22         customer_city             69
23      customer_country             21
24         employee_name              9
25        employee_title              3
26         employee_city              2
27      employee_country              2
28            reports_to              3
29          shipper_name              3
30            line_total           1149
31            order_year              3
32           order_month             12
33         order_quarter              4
34       ship_delay_days             35

## 16. Value Counts — Key Categorical Columns

In [16]:
print('--- categoryName ---')
print(df['categoryName'].value_counts())
print()
print('--- customer_country ---')
print(df['customer_country'].value_counts())
print()
print('--- employee_name ---')
print(df['employee_name'].value_counts())
print()
print('--- shipper_name ---')
print(df['shipper_name'].value_counts())

--- categoryName ---
categoryName
Beverages           404
Dairy Products      366
Confections         334
Seafood             330
Condiments          216
Grains & Cereals    196
Meat & Poultry      173
Produce             136
Name: count, dtype: int64

--- customer_country ---
customer_country
USA            352
Germany        328
Brazil         203
France         184
UK             135
Austria        125
Venezuela      118
Sweden          97
Canada          75
Mexico          72
Belgium         56
Ireland         55
Finland         54
Spain           54
Italy           53
Switzerland     52
Denmark         46
Argentina       34
Portugal        30
Poland          16
Norway          16
Name: count, dtype: int64

--- employee_name ---
employee_name
Margaret Peacock    420
Nancy Davolio       345
Janet Leverling     321
Laura Callahan      260
Andrew Fuller       241
Robert King         176
Michael Suyama      168
Steven Buchanan     117
Anne Dodsworth      107
Name: count, dtype: int64

--- shipper_name ---
shipper_name
United Package      864
Speedy Express      646
Federal Shipping    645
Name: count, dtype: int64

---
# DATA CLEANING
---

## Step 1 : Make a Copy of the Raw Data

In [17]:
df_raw = df.copy()   # keep original untouched
df_clean = df.copy() # all cleaning done on this copy

print('Raw shape   :', df_raw.shape)
print('Clean shape :', df_clean.shape)

Raw shape   : (2155, 35)
Clean shape : (2155, 35)

## Step 2 : Fix Data Types — Convert Date Columns (object → datetime)

In [18]:
date_cols = ['orderDate', 'requiredDate', 'shippedDate']

for col in date_cols:
    df_clean[col] = pd.to_datetime(df_clean[col], errors='coerce')

print('Date column dtypes after conversion:')
print(df_clean[date_cols].dtypes)

Date column dtypes after conversion:
orderDate       datetime64[ns]
requiredDate    datetime64[ns]
shippedDate     datetime64[ns]
dtype: object

## Step 3 : Fix Data Types — discontinued Column (int → bool)

In [19]:
# Before
print('Before:', df_clean['discontinued'].dtype, '| Values:', df_clean['discontinued'].unique())

df_clean['discontinued'] = df_clean['discontinued'].astype(bool)

# After
print('After :', df_clean['discontinued'].dtype, '| Values:', df_clean['discontinued'].unique())

Before: int64 | Values: [0 1]
After : bool | Values: [False  True]

## Step 4 : Fix Data Types — reports_to Column (float → Int64, nullable integer)

In [20]:
# reports_to is float because of NaN values
# Use pandas nullable integer type Int64 (capital I) to keep NaN support
print('Before:', df_clean['reports_to'].dtype)
print(df_clean['reports_to'].value_counts(dropna=False))

df_clean['reports_to'] = df_clean['reports_to'].astype('Int64')

print('After :', df_clean['reports_to'].dtype)

Before: float64
reports_to
8.0    1086
5.0     451
2.0     377
NaN     241
Name: count, dtype: int64
After : Int64

## Step 5 : Fix Floating Point Precision in line_total

In [21]:
# Example of floating point issue: 1261.3999999999999 should be 1261.40
print('Before rounding (sample):')
print(df_clean[df_clean['line_total'] != round(df_clean['line_total'], 2)]['line_total'].head(5).values)

df_clean['line_total'] = df_clean['line_total'].round(2)

print('After rounding (sample):')
print(df_clean['line_total'].head(5).values)

Before rounding (sample):
[604.8   122.88  163.2   163.625 346.56 ]
After rounding (sample):
[ 168.    98.   174.   167.4 1696. ]

## Step 6 : Remove Redundant Column — product_unitPrice

In [22]:
# unitPrice (from order_details) = actual price at time of order
# product_unitPrice (from products) = current catalogue price
# We keep unitPrice (transactional) and drop product_unitPrice (catalogue)

print('Columns before:', df_clean.shape[1])
df_clean.drop(columns=['product_unitPrice'], inplace=True)
print('Columns after :', df_clean.shape[1])
print('Dropped: product_unitPrice')

Columns before: 35
Columns after : 34
Dropped: product_unitPrice

## Step 7 : Handle Missing Values — shippedDate and ship_delay_days

> These 73 rows are orders that have NOT yet been shipped (no ship date = valid business reason).  
> We DO NOT drop them — instead we flag them with a new column `is_shipped`.

In [23]:
# Flag unshipped orders
df_clean['is_shipped'] = df_clean['shippedDate'].notna()

print('Shipped orders     :', df_clean['is_shipped'].sum())
print('Not shipped orders :', (~df_clean['is_shipped']).sum())

# ship_delay_days is NaN where order is not shipped — correct, leave as-is
print('Missing shippedDate    :', df_clean['shippedDate'].isnull().sum())
print('Missing ship_delay_days:', df_clean['ship_delay_days'].isnull().sum())

Shipped orders     : 2082
Not shipped orders : 73
Missing shippedDate    : 73
Missing ship_delay_days: 73

## Step 8 : Handle Missing Values — reports_to

> `reports_to` is null for the top-level manager (no one to report to).  
> This is intentional — we fill with 0 to indicate no manager.

In [24]:
print('Missing reports_to before:', df_clean['reports_to'].isnull().sum())

df_clean['reports_to'] = df_clean['reports_to'].fillna(0).astype('Int64')

print('Missing reports_to after :', df_clean['reports_to'].isnull().sum())
print('Value counts:')
print(df_clean['reports_to'].value_counts())

Missing reports_to before: 241
Missing reports_to after : 0
Value counts:
reports_to
8    1086
5     451
2     377
0     241
Name: count, dtype: Int64

## Step 9 : Remove Duplicate Rows (if any)

In [25]:
before = df_clean.shape[0]
df_clean.drop_duplicates(inplace=True)
after = df_clean.shape[0]

print(f'Rows before : {before}')
print(f'Rows after  : {after}')
print(f'Duplicates removed: {before - after}')

Rows before : 2155
Rows after  : 2155
Duplicates removed: 0

## Step 10 : Standardize Text Columns — Strip Whitespace

In [26]:
text_cols = df_clean.select_dtypes(include='object').columns.tolist()

for col in text_cols:
    df_clean[col] = df_clean[col].str.strip()

print(f'Stripped whitespace from {len(text_cols)} text columns:')
print(text_cols)

Stripped whitespace from 15 text columns:
['productName', 'quantityPerUnit', 'categoryName', 'category_description', 'customerID', 'customer_company', 'customer_contact', 'customer_title', 'customer_city', 'customer_country', 'employee_name', 'employee_title', 'employee_city', 'employee_country', 'shipper_name']

## Step 11 : Validate — Quantity and Price Must Be Positive

In [27]:
invalid_qty   = df_clean[df_clean['quantity'] <= 0]
invalid_price = df_clean[df_clean['unitPrice'] <= 0]
invalid_total = df_clean[df_clean['line_total'] < 0]

print(f'Rows with quantity <= 0  : {len(invalid_qty)}')
print(f'Rows with unitPrice <= 0 : {len(invalid_price)}')
print(f'Rows with line_total < 0 : {len(invalid_total)}')

Rows with quantity <= 0  : 0
Rows with unitPrice <= 0 : 0
Rows with line_total < 0 : 0

## Step 12 : Validate — Discount Must Be Between 0 and 1

In [28]:
invalid_discount = df_clean[(df_clean['discount'] < 0) | (df_clean['discount'] > 1)]

print(f'Rows with invalid discount (outside 0-1): {len(invalid_discount)}')
print('Discount value range:')
print(df_clean['discount'].describe())

Rows with invalid discount (outside 0-1): 0
Discount value range:
count    2155.000000
mean        0.056167
std         0.083450
min         0.000000
25%         0.000000
50%         0.000000
75%         0.100000
max         0.250000
Name: discount, dtype: float64

## Step 13 : Validate — orderDate Must Be Before shippedDate

In [29]:
shipped_rows = df_clean[df_clean['shippedDate'].notna()].copy()
invalid_dates = shipped_rows[shipped_rows['shippedDate'] < shipped_rows['orderDate']]

print(f'Orders where shippedDate < orderDate (invalid): {len(invalid_dates)}')
if len(invalid_dates) == 0:
    print('All shipping dates are valid.')

Orders where shippedDate < orderDate (invalid): 0
All shipping dates are valid.

## Step 14 : Final Null Check After Cleaning

In [30]:
remaining_nulls = df_clean.isnull().sum()
remaining_nulls = remaining_nulls[remaining_nulls > 0]

if remaining_nulls.empty:
    print('No missing values remaining.')
else:
    print('Remaining missing values:')
    print(remaining_nulls)

Remaining missing values:
shippedDate        73
ship_delay_days    73
dtype: int64

## Step 15 : Cleaned Dataset — Final Info

In [31]:
print('=== CLEANED DATASET SUMMARY ===')
print(f'Shape        : {df_clean.shape}')
print(f'Total Orders : {df_clean["orderID"].nunique():,}')
print(f'Date Range   : {df_clean["orderDate"].min().date()} to {df_clean["orderDate"].max().date()}')
print(f'Total Revenue: ${df_clean["line_total"].sum():,.2f}')
print()
df_clean.info()

=== CLEANED DATASET SUMMARY ===
Shape        : (2155, 35)
Total Orders : 830
Date Range   : 2013-07-04 to 2015-05-06
Total Revenue: $1,265,793.02

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2155 entries, 0 to 2154
Data columns (total 35 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   orderID               2155 non-null   int64
 1   productID             2155 non-null   int64
 2   unitPrice             2155 non-null   float64
 3   quantity              2155 non-null   int64
 4   discount              2155 non-null   float64
 5   productName           2155 non-null   object
 6   quantityPerUnit       2155 non-null   object
 7   categoryID            2155 non-null   int64
 8   discontinued          2155 non-null   bool
 9   categoryName          2155 non-null   object
 10  category_description  2155 non-null   object
 11  customerID            2155 non-null   object
 12  employeeID            2155 non-null   int64
 13  orderDate             2155 non-null   datetime64[ns]
 14  requiredDate          2155 non-null   datetime64[ns]
 15  shippedDate           2082 non-null   datetime64[ns]
 16  shipperID             2155 non-null   int64
 17  freight               2155 non-null   float64
 18  customer_company      2155 non-null   object
 19  customer_contact      2155 non-null   object
 20  customer_title        2155 non-null   object
 21  customer_city         2155 non-null   object
 22  customer_country      2155 non-null   object
 23  employee_name         2155 non-null   object
 24  employee_title        2155 non-null   object
 25  employee_city         2155 non-null   object
 26  employee_country      2155 non-null   object
 27  reports_to            2155 non-null   Int64
 28  shipper_name          2155 non-null   object
 29  line_total            2155 non-null   float64
 30  order_year            2155 non-null   int64
 31  order_month           2155 non-null   int64
 32  order_quarter         2155 non-null   int64
 33  ship_delay_days       2082 non-null   float64
 34  is_shipped            2155 non-null   bool
dtypes: Int64(1), bool(2), datetime64[ns](3), float64(5), int64(9), object(15)
memory usage: 562.0+ KB

## Step 16 : Preview Cleaned Dataset

In [32]:
df_clean.head(10)

,orderID,productID,unitPrice,quantity,discount,productName,quantityPerUnit,categoryID,discontinued,categoryName,...,employee_city,employee_country,reports_to,shipper_name,line_total,order_year,order_month,order_quarter,ship_delay_days,is_shipped
0,10248,11,14.0,12,0.00,Queso Cabrales,1 kg pkg.,4,False,Dairy Products,...,London,UK,2,Federal Shipping,168.00,2013,7,3,12.0,True
1,10248,42,9.8,10,0.00,Singaporean Hokkien Fried Mee,32 - 1 kg pkgs.,5,True,Grains & Cereals,...,London,UK,2,Federal Shipping,98.00,2013,7,3,12.0,True
2,10248,72,34.8,5,0.00,Mozzarella di Giovanni,24 - 200 g pkgs.,4,False,Dairy Products,...,London,UK,2,Federal Shipping,174.00,2013,7,3,12.0,True
3,10249,14,18.6,9,0.00,Tofu,40 - 100 g pkgs.,7,False,Produce,...,London,UK,5,Speedy Express,167.40,2013,7,3,5.0,True
4,10249,51,42.4,40,0.00,Manjimup Dried Apples,50 - 300 g pkgs.,7,False,Produce,...,London,UK,5,Speedy Express,1696.00,2013,7,3,5.0,True
5,10250,41,7.7,10,0.00,Jack's New England Clam Chowder,12 - 12 oz cans,8,False,Seafood,...,New York,USA,8,United Package,77.00,2013,7,3,4.0,True
6,10250,51,42.4,35,0.15,Manjimup Dried Apples,50 - 300 g pkgs.,7,False,Produce,...,New York,USA,8,United Package,1261.40,2013,7,3,4.0,True
7,10250,65,16.8,15,0.15,Louisiana Fiery Hot Pepper Sauce,32 - 8 oz bottles,2,False,Condiments,...,New York,USA,8,United Package,214.20,2013,7,3,4.0,True
8,10251,22,16.8,6,0.05,Gustaf's Knackebröd,24 - 500 g pkgs.,5,False,Grains & Cereals,...,New York,USA,8,Speedy Express,95.76,2013,7,3,7.0,True
9,10251,57,15.6,15,0.05,Ravioli Angelo,24 - 250 g pkgs.,5,False,Grains & Cereals,...,New York,USA,8,Speedy Express,222.30,2013,7,3,7.0,True

## Step 17 : Export Cleaned Dataset

In [33]:
output_path = r'D:\Intern Project\Northwind Traders\northwind_cleaned.csv'
df_clean.to_csv(output_path, index=False)

print(f'Saved: northwind_cleaned.csv')
print(f'Shape: {df_clean.shape}')
print()
print('Cleaning Summary:')
print('  Fixed date columns        : orderDate, requiredDate, shippedDate -> datetime')
print('  Fixed discontinued        : int -> bool')
print('  Fixed reports_to          : float -> Int64, NaN filled with 0')
print('  Fixed line_total precision: rounded to 2 decimal places')
print('  Dropped redundant column  : product_unitPrice')
print('  Added flag column         : is_shipped (True/False)')
print('  Stripped whitespace       : all text columns')
print('  Validated                 : quantity, unitPrice, discount, date order')

Saved: northwind_cleaned.csv

Shape: (2155, 35)

Cleaning Summary:
  Fixed date columns        : orderDate, requiredDate, shippedDate -> datetime
  Fixed discontinued        : int -> bool
  Fixed reports_to          : float -> Int64, NaN filled with 0
  Fixed line_total precision: rounded to 2 decimal places
  Dropped redundant column  : product_unitPrice
  Added flag column         : is_shipped (True/False)
  Stripped whitespace       : all text columns
  Validated                 : quantity, unitPrice, discount, date order